@echo off
cd /d "d:\Github_projects\My-Portfolio\public\certifications"
rename "AI-for-beginners_HP-LIFEcertificate-1.png" "hp-ai.png"
rename "CertificateOfCompletion_Java Data Structures.png" "linkedin-java-ds.png"
rename "CertificateOfCompletion_Learning Java 11 (1)-1.png" "linkedin-java11.png"
rename "CertificateOfCompletion_Learning Linux Command Line 2023.png" "linkedin-linux.png"
rename "CertificateOfCompletion_Learning Next.png" "linkedin-nextjs.png"
rename "CertificateOfCompletion_Learning TypeScript.png" "linkedin-typescript.png"
rename "CertificateOfCompletion_Practical GitHub Actions-1.png" "linkedin-github.png"
rename "Coursera BEUTTPWU6O9E-1.png" "coursera-python.png"
rename "Introduction-to-Cybersecurity_HP-LIFE-1.png" "hp-cyber.png"
rename "JavaScript Bootcamp_LUEJSMAY1251087-1.png" "letsupgrade-js.png"
rename "LetsUpgrade-DSABootcamp_LUEDSAMAY125381-1.png" "letsupgrade-dsa.png"
rename "LetsUpgrade-JavaBootcamp_LUEJAVAAPR12599-1.png" "letsupgrade-java.png"
rename "Postman - Postman API Fundamentals Student Expert - 2025-04-27_page-0001.jpg" "postman-api.jpg"
rename "Python Bootcamp_LUEPYTMAY1251341.png" "letsupgrade-python.png"
rename "Python_for_Beginners_E-Certificate-1.png" "mora-python.png"
